#pragma config(Sensor, in1,    LiftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    FourBarPot,     sensorPotentiometer)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, in4,    BATERY_2_PORT,  sensorAnalog)
#pragma config(Sensor, dgtl1,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  test,           sensorRotation)
#pragma config(Sensor, dgtl8, OddLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl9, EvenLED,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl10,  GoliathEnc,     sensorRotation)
#pragma config(Sensor, dgtl11,  SonarR,         sensorSONAR_raw)
#pragma config(Motor,  port1,           DiffR,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LiftTop,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Base_R_F,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Base_L_F,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Base_R_M,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Base_B,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Base_L_M,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           goliathM,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftBottom,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          DiffL,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard '//

/*USE THIS LATER
#pragma config(Sensor, dgtl7,  SonarR,         sensorSONAR_inch)
#pragma config(Sensor, dgtl9,  SonarL,         sensorSONAR_inch)
*/
// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "include/worlds/randomstuff.h"
#include "include/worlds/initialize.h"
#include "include/worlds/sensor.h"
#include "include/worlds/base.h"
#include "include/worlds/lift.h"
#include "include/worlds/LCD.h"
#include "include/worlds/auton.h"

#define NONE 100
const bool rev = true;
//extern
struct PIDs;
struct liftMech;


struct sideBase;

void initializeOpControl(const bool driver) {
	SensorValue[EvenLED] = 0;
	SensorValue[OddLED] = 0;
	clearLCDLine(0);
	clearLCDLine(1);
	if(driver) resetGyros();//wastes time on auton
	resetEncoders();
	velocity = 0.0;
	//-LIFT---------&reference--TYPE----------sensor-1-----motor-1-----motor-2-------max------min-----isReversed? (opt)
	initLiftType(   &mainLift,  NOPID,       LiftPot,     LiftTop,    LiftBottom,   3365,    1700                );
	initLiftType(   &MoGo,      DIFFERENTIAL, NONE,        LiftTop,    LiftBottom,   1,       -1                );
	initLiftType(   &FourBar,   BINARY,       FourBarPot,  DiffL,      DiffR,        3000,    1160           );
	initLiftType(   &goliat,    HOLD,         GoliathEnc,  goliathM,   goliathM,     100000,  -100000          );

	//-PID------&reference------sensor--------------thresh--kP------kI------kD------reversed----running(opt)----
	initPID(    &mainLift.PID,  mainLift.sensor,    40,    0.15,    0.0,    0.1,   rev,        false         );
	initPID(    &FourBar.PID,   FourBar.sensor,     100,   	0.2,     0.0,    0.0,    rev,        false         );
	//initPID(    &gyroBase,      Gyro,               3,      0.525,  0.0,    0.5,    !rev,       false         );

	//-SIDE---------&reference----sensor------------motor-1------motor-2--------motor-3------
	initSideBase(   &Left,        RightEncoder,      Base_L_F,    Base_L_M,      NONE        );
	initSideBase(   &Right,       RightEncoder,     Base_R_F,    Base_R_M,      NONE        );
	//initSideBase(   &goliat,      GoliathEnc,  		goliathM,     NONE,          NONE       );
	pastRot = 0;
}

void pre_auton() {//dont care
	SensorType[Gyro] = sensorGyro;
	wait1Msec(1224);
	//Adjust SensorScale to correct the scaling for your gyro
	scaleGyros();
	startTask(displayLCD);
	while( bIfiRobotDisabled ){//in preauton...bIfiRobotDisabled ||
		autonSelect(nLCDButtons);
		delay(50);
	}
}
void spike(){
	mainLift.PID.goal = mainLift.min + 300;
	mainLift.PID.isRunning = true;
	rotFor(20);
}
task MoGoOut(){
	intakeSpeed = INSPEED/2;//keeps cone intaken
	UpUntil(&mainLift, SensorValue[mainLift.sensor] + 300);
	mainLift.PID.goal = SensorValue[mainLift.sensor] + 300;
	//FourBar.PID.goal = FourBar.min;
	clearTimer(T2);
	while(time1[T2] < 600){
		liftDiff(&MoGo, 127);
		//liftMove(&FourBar, -127);
	}
	return;
}
void MoGoAndPreload(){
	//startTask(goliatTask);
	startTask(MoGoOut);
	FourBar.PID.goal = FourBar.min;
	FourBar.PID.isRunning = true;
	driveFor(44);
	stopTask(MoGoOut); //stop before lift moves
	mainLift.PID.goal = mainLift.min;
	intakeSpeed = -80;
	delay(200);
	mainLift.PID.goal = mainLift.min + 300;
	clearTimer(T4);
	while(time1[T4] < 900) liftDiff(&MoGo, -127);
	liftMove(&MoGo, 0);
	intakeSpeed = INSPEED;
	currentCone = 1;//added  1 to MoGo
	return;
}
task stackTask(){
	stackUp();
	FourBar.PID.goal = FourBar.max + 200;
	FourBar.PID.isRunning = true;
	intakeSpeed = -127;
	delay(200);
	mainLift.PID.goal = avg2(mainLift.max, mainLift.min); //lift lift
	mainLift.PID.isRunning = true;
	//FourBar.PID.isRunning = false;
	return;
}
void stackCones(int coneNum){
	for(int j=1; j<coneNum; j++){ //do one less
		driveFor(5, initDir);
		FourBar.PID.goal = FourBar.min;
		//DownUntil(&mainLift, mainLift.min+10, 127); //go for next cone
		mainLift.PID.goal = mainLift.min-100;
		delay(200);
		mainLift.PID.isRunning = true;
		intakeSpeed = INSPEED;
		delay(400);
		stackUp();
		mainLift.PID.goal = heightValues[currentCone]-100;
		mainLift.PID.isRunning = true;
		FourBar.PID.goal = FourBar.max + 300;
		FourBar.PID.isRunning = true;
		delay(50);
		intakeSpeed = OUTSPEED;
		delay(150);
		FourBar.PID.goal = FourBar.min;
		mainLift.PID.goal = heightValues[currentCone]+100;
	}
	//final cone is stacked while driving back
	driveFor(5, initDir);
	FourBar.PID.goal = FourBar.min;
	//DownUntil(&mainLift, mainLift.min+10, 127); //go for next cone
	mainLift.PID.goal = mainLift.min-100;
	delay(200);
	mainLift.PID.isRunning = true;
	intakeSpeed = INSPEED;
	delay(600);
	startTask(stackTask);
}
void stackAuton(bool isSpiking, int cones, bool isRight, bool isTwenty){ //cones not including preload
	int dir  = 1;
	if(!isRight) dir = -1;
	initDir =  SensorValue[Gyro] * GyroK;
	if(isSpiking)spike();//not finished
	MoGoAndPreload();
	stackCones(cones);
	if(isTwenty){ //score in 20pt
		driveFor(-52);//drive back
		if (isRight) RSwingFor(-45);
		else LSwingFor(40);
		if(!isRight)	driveFor(-10); //drive to center of zone (-11)
		else driveFor(-10);
		rotFor(-dir * 90, 2);
		mainLift.PID.isRunning = false;
		fwds(127);//enter 20pt zone
		delay(1200);//drive fwds first for a lil bit
		liftDiff(&MoGo, 127);//MoGo out
		fwds(127);//whilst driving
		delay(450);
		fwds(0);
		liftDiff(&MoGo, 0);
		fwds(-127);
		liftDiff(&MoGo, -100);
		delay(50);
		liftDiff(&MoGo, 0);
		fwds(0);
		driveFor(-17);//exit zones
	}
	else { //score in 10 pt
		driveFor(-40);//drive back
		mainLift.PID.goal = avg2(mainLift.max, mainLift.min); //lift lift
		mainLift.PID.isRunning = true;
		if (isRight) RSwingFor(-45);//swing out
		else LSwingFor(45);
		rotFor(dir * -90, 1); //rotate perp to 10pt pole
		delay(100);
		driveFor(4); //drive to 10pt
		//mainLift.PID.isRunning = false;
		clearTimer(T4);
		while (SensorValue[MoGo.sensor] > MoGo.min && time1[T4] < 600) { //MoGo out
			liftDiff(&MoGo, 127);
		}
		//mainLift.PID.isRunning = true;
		driveFor(-20);// release & get out of the way
	}
}
void loaderAuton(bool isRight, bool isScored) {
	int dir  = 1;
	if(!isRight) dir = -1;
	MoGoAndPreload();
	mainLift.PID.goal = mainLift.min+500;
	mainLift.PID.isRunning = true;
	driveFor(-27);
	curveFor(45, 2); //curve into position
	intakeSpeed = INSPEED;
}

void testing(){
	//playSound(soundUpwardTones);
	currentCone = 0;
	//stackUp();
	//stackDown();
	//delay(5000);
	stackAuton(false, 2,LEFTside,TWENTY);
}
task autonomous() {
	autonRunning = true;
	initializeOpControl(false);//autonomous init
	startTask(LiftControlTask);//individual pid for lift type
	startTask(MeasureSpeed);//velocity measurer for base
	startTask(displayLCD);
	//startTask(goliatTask);
	currentCone = 0;
	if(currentAutonomous == 0) testing(); //autonTest(1, RIGHTside, TWENTY);
	else if(currentAutonomous == 1) stackAuton(false, 1, LEFTside, TWENTY);
	else if(currentAutonomous == 2) stackAuton(false, 1, RIGHTside, TEN);
	else if(currentAutonomous == 3) stackAuton(false, 1, LEFTside, TEN);
	autonRunning = false;
	return;
}
task usercontrol() {//initializes everything~
	initializeOpControl(true);//driver init
	startTask(LiftControlTask);//individual pid for lift type
	startTask(MeasureSpeed);//velocity measurer for base
	startTask(autoStack);
//s	startTask(antiStall);
	startTask(manualGoliath);//controls goliath
	//startTask(killswitch);
	if(slewRating) startTask(MotorSlewRateTask);
	startTask(displayLCD);
	autonRunning = false;
	bLCDBacklight = false;// Turn on LCD Backlight
	clearLCDLine(0); // Clear line 1 (0) of the LCD
	clearLCDLine(1); // Clear line 2 (1) of the LCD
	if(nImmediateBatteryLevel < 8200) playSound(soundException);
	else playSound(soundUpwardTones);
	for (;;) {
		driveCtrlr();
		//if(U7) testing();//stackAuton(1, LEFTside, TWENTY);//sonarLock();
		//if(D7) testing();//MoGoAndPreload();//sonarLock();
		//if(L7) stackUp();//sonarLock();
		//if(R7) standStack(currentCone);//sonarLock();
		delay(15);
	}
}//function for operator control
