#pragma config(Sensor, in1,    LiftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    FourBarPot,     sensorPotentiometer)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, in4,    BATERY_2_PORT,  sensorAnalog)
#pragma config(Sensor, in5,    MoGoPot,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  test,           sensorRotation)
#pragma config(Sensor, dgtl8,  OddLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  EvenLED,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, GoliathEnc,     sensorRotation)
#pragma config(Sensor, dgtl11, SonarR,         sensorSONAR_raw)
#pragma config(Motor,  port1,           DiffR,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LiftTop,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Base_R_F,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Base_L_F,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Base_R_M,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Base_B,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Base_L_M,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           goliathM,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftBottom,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          DiffL,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard '//

/*USE THIS LATER
#pragma config(Sensor, dgtl7,  SonarR,         sensorSONAR_inch)
#pragma config(Sensor, dgtl9,  SonarL,         sensorSONAR_inch)
*/
// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "include/worlds/randomstuff.h"
#include "include/worlds/initialize.h"
#include "include/worlds/sensor.h"
#include "include/worlds/base.h"
#include "include/worlds/lift.h"
#include "include/worlds/LCD.h"
#include "include/worlds/auton.h"

#define NONE 100
const bool rev = true;
//extern
struct PIDs;
struct liftMech;


struct sideBase;

void initializeOpControl(const bool driver) {
	SensorValue[EvenLED] = 0;
	SensorValue[OddLED] = 0;
	clearLCDLine(0);
	clearLCDLine(1);
	if(driver) resetGyros();//wastes time on auton
	resetEncoders();
	velocity = 0.0;
	//-LIFT---------&reference--TYPE----------sensor-1-----motor-1-----motor-2-------max------min-----isReversed? (opt)
	initLiftType(   &mainLift,  NORMAL,       LiftPot,     LiftTop,    LiftBottom,   3365,    1700                );
	initLiftType(   &MoGo,      DIFFERENTIAL, MoGoPot,     LiftTop,    LiftBottom,   2220,    380   );
	initLiftType(   &FourBar,   BINARY,       FourBarPot,  DiffL,      DiffR,        3200,    1160           );
	initLiftType(   &goliat,    HOLD,         GoliathEnc,  goliathM,   goliathM,     100000,  -100000          );

	//-PID------&reference------sensor--------------thresh--kP------kI------kD------reversed----running(opt)----
	initPID(    &mainLift.PID,  mainLift.sensor,    40,    0.15,    0.0,    0.1,   rev,        false         );
	initPID(    &FourBar.PID,   FourBar.sensor,     100,   	0.2,     0.0,    0.0,    rev,        false         );
	//initPID(    &gyroBase,      Gyro,               3,      0.525,  0.0,    0.5,    !rev,       false         );

	//-SIDE---------&reference----sensor------------motor-1------motor-2--------motor-3------
	initSideBase(   &Left,        RightEncoder,      Base_L_F,    Base_L_M,      NONE        );
	initSideBase(   &Right,       RightEncoder,     Base_R_F,    Base_R_M,      NONE        );
	//initSideBase(   &goliat,      GoliathEnc,  		goliathM,     NONE,          NONE       );
	pastRot = 0;
}

void pre_auton() {//dont care
	SensorType[Gyro] = sensorGyro;
	wait1Msec(1224);
	//Adjust SensorScale to correct the scaling for your gyro
	scaleGyros();
	startTask(displayLCD);
	while( bIfiRobotDisabled ){//in preauton...bIfiRobotDisabled ||
		autonSelect(nLCDButtons);
		delay(50);
	}
}
void spike(){
	mainLift.PID.goal = mainLift.min + 300;
	mainLift.PID.isRunning = true;
	rotFor(20);
}

task autonGoliath(){
	while(autonRunning) liftMove(&goliat, intakeSpeed);
	liftMove(&goliat, 0);
}
task MoGoOut(){
	intakeSpeed = 127;//keeps cone intaken
	MoGo.PID.isRunning = false;
	UpUntil(&mainLift, SensorValue[mainLift.sensor] + 300);
	mainLift.PID.goal = SensorValue[mainLift.sensor] + 200;
	FourBar.PID.goal = FourBar.min;
	DownUntil(&MoGo, MoGo.min, 127);
	return;
}
task MoGoIn(){
	UpUntil(&MoGo, MoGo.max, 127);
	return;
}
void MoGoAndPreload(){
	autonRunning = true;
	startTask(MoGoOut);
	FourBar.PID.isRunning = true;
	intakeSpeed = 127;
	driveFor(44);
	stopTask(MoGoOut);
	mainLift.PID.isRunning = true;
	mainLift.PID.goal = mainLift.min;
	intakeSpeed = -127;
	delay(200);
	UpUntil(&mainLift, SensorValue[mainLift.sensor] + 150, 127);
	startTask(MoGoIn);
	delay(250);
	currentCone = 1;//added  1 to MoGo
	return;
}
void waitForPickup(){
	clearTimer(T1);
	while(goliat.velocity > 15 && time1[T1] < 800){
		fwds(25);//move fwds sligtly
		liftMove(&FourBar, -40);
		liftMove(&mainLift, -40);
		delay(10);
	}
	fwds(0);
	intakeSpeed = 127;
	return;
}
void stackCone(){
	intakeSpeed = 127;//holding cone
	UpUntilW4Bar(heightValues[currentCone-1], 0.89, 100, true);
	FourBar.PID.goal = FourBar.max;
	delay(350);
	liftMoveT(&mainLift, -70, 150);
	intakeSpeed = -127;
	liftMove(&mainLift, 0);
	delay(50);
	liftMoveT(&mainLift, 110, 250);
}
void driveToCone(){
	FourBar.PID.goal = FourBar.min-100;
	driveFor(5, initDir);
	intakeSpeed = 127;
	mainLift.PID.goal = mainLift.min - 100;
	mainLift.PID.isRunning = true;
	DownUntil(&mainLift, mainLift.min+100, 127);
	waitForPickup();//waits to pickup cone
}
task stackTask(){
	stackCone();
	mainLift.PID.goal = 2200;
	mainLift.PID.isRunning = true;
	intakeSpeed = 0;
}
void stackCones(int coneNum){
	MoGo.PID.isRunning = false;
	for(int j=0; j<coneNum-1; j++){ //do one less
		driveToCone();
		stackCone();
	}
	if(coneNum == 2) driveToCone();
	else {
		FourBar.PID.goal = FourBar.min-100;
		intakeSpeed = 127;
		mainLift.PID.goal = mainLift.min - 100;
		mainLift.PID.isRunning = true;
		DownUntil(&mainLift, mainLift.min+100, 127);
		driveFor(4, initDir);
		waitForPickup();//waits to pickup cone
	}
	startTask(stackTask);//last one in a task
}
void scoreInTwenty(){
	fwds(127);
	delay(450);
	fwds(127);
	DownUntil(&MoGo, 1200, 127);
	fwds(90);
	liftDiff(&MoGo, -10);
	delay(230);
	liftDiff(&MoGo, -70);
	driveFor(-17);//exit zones
}
void stackAuton(bool isSpiking, int cones, bool isRight, bool isTwenty){ //cones not including preload
	int dir  = 1;
	if(!isRight) dir = -1;
	stoptask(manualGoliath);
	autonRunning = true;
	intakeSpeed = 127;
	startTask(autonGoliath);
	FourBar.PID.kP = 0.2;
	initDir =  SensorValue[Gyro] * GyroK;
	if(isSpiking)spike();//not finished
	MoGoAndPreload();
	stackCones(cones);
	if(isTwenty){ //score in 20pt
		driveFor(-(48 + cones*5.5));//drive back
		if (isRight) RSwingFor(-45);
		else LSwingFor(40);
		if(!isRight)	driveFor(-13); //drive to center of zone (-11)
	//	else driveFor(0);
		rotFor(-dir * 90, 2);
		mainLift.PID.goal = 2000;
		FourBar.PID.goal = FourBar.max;
		FourBar.PID.isRunning = true;
		mainLift.PID.isRunning = true;
		scoreInTwenty();
	}
	else { //score in 10 pt
		driveFor(-40);//drive back
		mainLift.PID.goal = avg2(mainLift.max, mainLift.min); //lift lift
		mainLift.PID.isRunning = true;
		if (isRight) RSwingFor(-45);//swing out
		else LSwingFor(45);
		rotFor(dir * -90, 1); //rotate perp to 10pt pole
		delay(100);
		driveFor(4); //drive to 10pt
		//mainLift.PID.isRunning = false;
		clearTimer(T4);
		while (SensorValue[MoGo.sensor] > MoGo.min && time1[T4] < 600) { //MoGo out
			liftDiff(&MoGo, 127);
		}
		//mainLift.PID.isRunning = true;
		driveFor(-20);// release & get out of the way
	}
	autonRunning = false;
	startTask(manualGoliath);
	return;
}
void loaderAuton(bool isRight, bool isScored) {
	int dir  = 1;
	if(!isRight) dir = -1;
	MoGoAndPreload();
	const int liftPos = 1850;
	FourBar.PID.goal = FourBar.max;
	mainLift.PID.goal = liftPos + 600; //go to loader height
	mainLift.PID.isRunning = true;
	waitTill(&MoGo, avg2(MoGo.min, MoGo.max), 100);
	driveFor(-14.5);
	rotFor(84, 2); //curve into position
	startTask(sonarLock);
	repeat(7){
		intakeSpeed = 127;
		FourBar.PID.goal = FourBar.min;
		if(SensorValue[mainLift.sensor] > liftPos + 350) DownUntil(&mainLift, liftPos+300, 90);
		else DownUntil(&mainLift, liftPos +100, 80);
		liftMove(&mainLift, 0);
		delay(400);
		mainLift.PID.goal = heightValues[currentCone] - 100;
		waitTill(&mainLift, mainLift.PID.goal, 100);
		liftMoveT(&FourBar, 127, 400);
		liftMoveT(&mainLift, -80, 100);
		intakeSpeed = -80;
		liftMoveT(&mainLift, -80, 100);
		liftMoveT(&mainLift, 80, 200);
		currentCone++;
	}
	stopTask(sonarLock);
	fwds(0);
}

		/*intakeSpeed = 127;
		FourBar.PID.goal = FourBar.min;
		if(SensorValue[mainLift.sensor] > liftPos + 350) DownUntil(&mainLift, liftPos+300, 90);
		else DownUntil(&mainLift, liftPos +100, 80);
		liftMove(&mainLift, 0);
		mainLift.PID.goal = liftPos;
		delay(100);
		UpUntil(&mainLift, heightValues[currentCone] - 80, 100);
		FourBar.PID.goal = FourBar.max;
		delay(250);
		liftMoveT(&mainLift, -80, 100);
		intakeSpeed = -80;
		liftMoveT(&mainLift, -80, 100);
		FourBar.PID.goal = FourBar.max;
		UpUntil(&mainLift, SensorValue[mainLift.sensor] + 200, 127);
		currentCone++;*/
task autonomous() {
	autonRunning = true;
	initializeOpControl(false);//autonomous init
	startTask(LiftControlTask);//individual pid for lift type
	startTask(MeasureSpeed);//velocity measurer for base
	startTask(displayLCD);
	startTask(autonGoliath);
	currentCone = 0;
	if(currentAutonomous == 0) loaderAuton(false, false);//stackAuton(false, 3, LEFTside, TWENTY);
	else if(currentAutonomous == 1) stackAuton(false, 3, RIGHTside, TWENTY);
	else if(currentAutonomous == 2) stackAuton(false, 2, RIGHTside, TEN);
	else if(currentAutonomous == 3) stackAuton(false, 2, LEFTside, TEN);
	autonRunning = false;
	return;
}
task usercontrol() {//initializes everything~
	initializeOpControl(true);//driver init
	startTask(LiftControlTask);//individual pid for lift type
	startTask(MeasureSpeed);//velocity measurer for base
	startTask(autoStack); //there are buttons double mapped in main
	//startTask(antiStall);
	startTask(manualGoliath);//controls goliath
	//startTask(killswitch);
	if(slewRating) startTask(MotorSlewRateTask);
	startTask(displayLCD);
	autonRunning = false;
	bLCDBacklight = false;// Turn on LCD Backlight
	clearLCDLine(0); // Clear line 1 (0) of the LCD
	clearLCDLine(1); // Clear line 2 (1) of the LCD
	if(nImmediateBatteryLevel < 8200) playSound(soundException);
	else playSound(soundUpwardTones);
	for (;;) {
		driveCtrlr();
		if(U7) loaderAuton(false, false);//stackAuton(false, 3, true, true);//MoGoAndPreload();
		/*if(U7) {
			autonRunning = true;
			/*while (SensorValue[MoGo.sensor] > MoGo.min){
				liftDiff(&MoGo, 127);
			}
			liftDiff(&MoGo, 0);*/ //works
			//mainLift.PID.isRunning = false;
			/*
			while(time1[T2] <500){
				DownUntil(&MoGo, MoGo.min);
			}
			MoGo.PID.isRunning = false;
		}
		if(D7) {
			playSound(soundBeepBeep);
			autonRunning = true;
			while(SensorValue[MoGoPot] < MoGo.max){
				liftDiff(&MoGo, -60);
			}
			liftDiff(&MoGo, 0);
			MoGo.PID.isRunning = false;
			playSound(soundBeepBeep);
		}
		//if(D7) testing();//MoGoAndPreload();//sonarLock();
		//if(R7) stackAuton(false, 3, true, true);
		if(L7) MoGoAndPreload();//standStack(currentCone);//sonarLock();*/
		delay(15);
	}
}//function for operator control
